#!/bin/bash

# LFIBay - Quick Start Guide
# This script demonstrates the installation and basic usage

echo "=========================================="
echo "LFIBay - Quick Start Guide"
echo "=========================================="
echo ""

# Step 1: Install dependencies
echo "[1/3] Installing dependencies..."
echo "Run: pip install -r requirements.txt"
echo ""
echo "This will install:"
echo "  - requests (HTTP client)"
echo "  - selenium (browser automation)"
echo "  - beautifulsoup4 (HTML parsing)"
echo "  - lxml (XML/HTML processing)"
echo "  - colorama (colored terminal output)"
echo ""

# Step 2: Setup ChromeDriver (if needed)
echo "[2/3] ChromeDriver Setup"
echo ""
echo "Selenium requires ChromeDriver to control Chrome browser."
echo "Most systems can auto-install it, but if you get errors:"
echo ""
echo "  Ubuntu/Debian:"
echo "    sudo apt-get install chromium-chromedriver"
echo ""
echo "  macOS:"
echo "    brew install --cask chromedriver"
echo ""
echo "  Or download from: https://chromedriver.chromium.org/"
echo ""

# Step 3: Run the tool
echo "[3/3] Running LFIBay"
echo ""
echo "Run: python3 lfibay.py"
echo ""
echo "The tool will:"
echo "  1. Ask for login URL"
echo "  2. Open browser for you to login manually"
echo "  3. Extract cookies automatically"
echo "  4. Ask for upload form URL"
echo "  5. Test 168 LFI payloads"
echo "  6. Generate reports in output/reports/"
echo ""

echo "=========================================="
echo "⚠️  IMPORTANT SECURITY WARNING ⚠️"
echo "=========================================="
echo "Only use this tool on systems you own or"
echo "have explicit written permission to test."
echo "Unauthorized access is illegal."
echo "=========================================="
echo ""

echo "Sample Workflow:"
echo "----------------"
echo "$ python3 lfibay.py"
echo ""
echo "[?] Enter login URL: https://target.com/login"
echo "[*] Opening browser... Login manually then press Enter"
echo "[+] Cookies extracted: 5 cookies"
echo "[+] WAF detected: Cloudflare"
echo ""
echo "[?] Enter upload form URL: https://target.com/upload"
echo "[*] Loading payloads... 168 payloads loaded"
echo "[*] Starting tests with 1-3s delay..."
echo ""
echo "Testing Payloads |████████████| 100.0% (168/168)"
echo ""
echo "[+] Found 12 successful payloads"
echo "[+] Report saved: output/reports/report_2025-11-25_21-13.html"
echo ""

echo "For full documentation, see README.md"
